version: "3.7"
services:
  identidock:
    build: .
    ports:
      - "5000:5000"
    networks:
      - identinet
  dnmonstre:
    image: amouat/dnmonster:1.0
    networks:
      - identinet

  redis:
    image: redis
    networks:
      - identinet

networks:
  identinet:
    driver: bridge